version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  e2eTest:
    docker:
      - image: circleci/node:14.8.0

    steps:
      - checkout

      - restore_cache:
          name: Restore yarn package cache
          key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Install Expo CLI
          command: npm install expo-cli 
      
      - save_cache:
          name: Save yarn package cache
          paths:
            - ~/.cache/yarn
          key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}

      - run:
          name: Login into Expo
          command: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD

      - run:
          name : App upload and Set app id in environment variable.
          command : |
            APK_PATH=$(npx expo url:apk)
            APP_UPLOAD_RESPONSE=$(curl -u "johncarlodeleon1:EPnWvRvF8sxcKEC9xpat" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "url=$APK_PATH")
            APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
            if [ $APP_ID != null ]; then
              echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
              echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
              source $BASH_ENV;
              echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
            else
              UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
              echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
              exit 1;
            fi


workflows:
  node-tests:
    jobs:
      - node/test
      - e2eTest:
          filters:
              branches:
                only: master